name: Quememareo
version: '1.0'
main: org.carpincho.queMeMareo.QueMeMareo
api-version: '1.21'
author: carpinchogaucho


commands:
  startGame:
    description: Inicia el juego Que me Mareo.
    usage: /startGame
    permission: queMeMareo.iniciarJuego
    permission-message: No tienes permiso para iniciar el juego.


  stopgame:
    description: Detiene el juego
    usage: /<command>
    permission: queMeMareo.stop
    permission-message: No tienes permisos para ejecutar este comando.

  restarPuntos:
    description: Resta 20 puntos a un jugador.
    usage: /restarPuntos <jugador>
    permission: queMeMareo.restarpuntos


  balance-start:
    description: Inicia el minijuego de balanceo de libros.
    usage: /balance-start [round]
    permission: bookbalance.admin
    permission-message: No tienes permiso para usar este comando.
    balance-register:
      description: Registra jugadores.
      usage: /balance-register [player]
      permission: bookbalance.admin
      permission-message: No tienes permiso para usar este comando.

  permissions:
    bookbalance.admin:
      description: Permite a los administradores iniciar el juego para otros jugadores.
      default: op

  stopmissuniverso:
    description: Detiene la partida de Miss Universo.
    usage: /stopmissuniverso
    permission: queMeMareo.stop